# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0002_auto_20170908_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
