# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import resttutorial.utils


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0003_information_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=resttutorial.utils.upload_image_path),
        ),
    ]
